name: Build et Push sur Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Build and Push
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t zacharyakakpo/20211279:latest . --push
