name: github-action

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install and run hadolint
      run: |
        sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.4.1/hadolint-Linux-x86_64
        sudo chmod +x /bin/hadolint
        hadolint Dockerfile
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: |
        az acr login --name ${{ secrets.REGISTRY_LOGIN_SERVER }}

    - name: Build the Docker image
      run: docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/acr_repo_zach:latest

    - name: Push the Docker image to ACR
      run: |
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/acr_repo_zach:latest

    - name: Deploy to ACI
      uses: azure/aci-deploy@v1
      with:
        resource_group: ${{ secrets.RESOURCE_GROUP }}
        name: ACI_Zach
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/acr_repo_zach:latest
        dns_name_label: devops
        location: france central
        registry_login_server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry_username: ${{ secrets.REGISTRY_USERNAME }}
        registry_password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Logout of Azure
      run: |
        az logout
