name: Build et Push sur Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build et Push Docker image
      if: steps.hadolint.outcome == 'success'
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your-dockerhub-username/your-image-name:latest

      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint@v2.7.0
        with:
          files: Dockerfile
        id: hadolint

      
