name: Build et Push sur Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Build and Push
        run: |
          docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
          docker buildx build --platform linux/amd64,linux/arm64 -t your-dockerhub-username/your-image-name:latest . --push
