name: github-action

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install and run hadolint
      run: |
        sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.4.1/hadolint-Linux-x86_64
        sudo chmod +x /bin/hadolint
        hadolint Dockerfile
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: |
        az acr login --name ${{ secrets.REGISTRY_LOGIN_SERVER }}

    - name: Build the Docker image
      run: docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/20211279:v1

    - name: Push the Docker image to ACR
      run: |
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/20211279:v1

    - name: Deploy to ACI
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        name: 20211279
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/20211279:v1
        dns-name-label: devops-20211279
        location: france central
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }} 
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        ports: 8081

    - name: Logout of Azure
      run: |
        az logout
